name: Bump Version & Tag

on:
  push:
    branches:
      - main

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Check Version
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: ""
          major_pattern: "BREAKING CHANGE"
          minor_pattern: "feat"
          search_commit_body: true

      - name: Push Tag
        run: |
          echo "Creating and pushing tag: ${{ steps.semver.outputs.version }}"
          git tag ${{ steps.semver.outputs.version }}
          git push https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }} ${{ steps.semver.outputs.version }}

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build & Publish
        run: |
          echo "Publishing version: $VERSION"
          ./gradlew publish
        env:
          VERSION: ${{ steps.semver.outputs.version }}
          PACKAGES_URL: ${{ secrets.PACKAGES_URL }}
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}
